def COLOR_MAP = [ 
    'SUCCESS': 'good', 
    'FAILURE': 'danger' 
]
pipeline {
    agent any
    tools {
        maven "MAVEN3.9.9"
        jdk "JDK17"
    }
    
    environment {
        cluster = 'vproappProd'
        service = 'vprofileapptask-service-prod'
    }

    stages {
        stage('Deploy to ecs') {
          steps {
            withAWS(credentials: 'awscreds', region: 'us-east-1') {
            sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
               }
          }
        }
    }
    post { 
        always { 
            slackSend( 
                channel: '#devopscicd', 
                color: COLOR_MAP[currentBuild.currentResult], 
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n${env.BUILD_URL}" 
            ) 
        } 
    } 
}